In [1]:
# Working with Dictionary and DataFrames

In [2]:
# Part 1: Working with Dictionary

In [32]:
# A data structure used to store data in key-value pairs. 
# It is a collection of unordered, mutable, and indexed data. Each key is unique and maps to a value.
Student = {
    "Name": ("Subhash Kumar"),
    "Age": 23,
    "faculty": "BCE"
}   
print(Student)

{'Name': 'Subhash Kumar', 'Age': 23, 'faculty': 'BCE'}

In [10]:
#creating a dictionary
Student = {
    "Name": ["Subhash", " Kumar"],
    "Age": 23,
    "faculty": "BCE"
}   
print(Student)

{'Name': ['John', 'Doe'], 'Age': 23, 'faculty': 'BCE'}

In [13]:
#Accessing values from the dictionary
print(Student["Name"])
print(Student["Age"])
print(Student["faculty"])

print(Student.get("Name")[0])

['John', 'Doe']
23
BCE
John

In [7]:
#use get() method to acess values from the dictionary
print(Student.get("Name"))
print(Student.get("Age"))
print(Student.get("faculty"))

Subhash

In [17]:
#Adding a new key-value pair to the dictionary
Student["Department"] = "Computer Science"
print(Student)

{'Name': 'Subhash Kumar', 'Age': 23, 'faculty': 'BCE', 'Department': 'Computer Science'}

In [24]:
# update value of existing key
Student["Age"] = 24  # update age from 23 to 24
print(Student["Age"])
print(Student)

24
{'Name': 'Subhash Kumar', 'Age': 24, 'faculty': 'BCE', 'Department': 'Computer Science'}

In [25]:
# Remove items from the dictionary
del Student["faculty"]  # remove the key "faculty" and its value
print(Student)

{'Name': 'Subhash Kumar', 'Age': 24, 'Department': 'Computer Science'}

In [28]:
# Remove items from the dictionary using pop() method
Student.pop("Department")  
print(Student)

{'Name': 'Subhash Kumar', 'Age': 24}

In [29]:
# Remove last items from the dictionary
Student.popitem() 
print(Student)

{'Name': 'Subhash Kumar'}

In [31]:
# Clear Dictionary
Student.clear()
print(Student)

{}

In [33]:
# Copying a dictionary

# Create a copy of the dictionary
Student_copy = Student.copy()
print(Student_copy)

{'Name': 'Subhash Kumar', 'Age': 23, 'faculty': 'BCE'}

In [38]:
# Get All Keys from the dictionary
print(Student_copy.keys())

# Get All Values from the dictionary
print(Student_copy.values())

# Get All Items from the dictionary
print(Student_copy.items())

dict_keys(['Name', 'Age', 'faculty'])
dict_values(['Subhash Kumar', 23, 'BCE'])
dict_items([('Name', 'Subhash Kumar'), ('Age', 23), ('faculty', 'BCE')])

In [40]:
#Check Keys Exits in the dictionary
print("Name" in Student) 
print("Age" in Student)

True
True

In [41]:
# get the length of the dictionary
print(len(Student))

3

In [43]:
#Loop through the dictionary and values
for key in Student:
    print(key, ":", Student[key])

Name : Subhash Kumar
Age : 23
faculty : BCE

In [44]:
#Loopthrough items in the dictionary
for key, value in Student.items():
    print(key, ":", value)

Name : Subhash Kumar
Age : 23
faculty : BCE

In [47]:
print(Student.items())

dict_items([('Name', 'Subhash Kumar'), ('Age', 23), ('faculty', 'BCE')])

In [49]:
#Part 2: Working with Pandas Data Frames

In [66]:
#creating a data frame containing student details such as Name, Age, and Faculty
import pandas as pd
Data = {
    "Name": ["Subhash", "Kumar", "Ravi", "Anil"],
    "Age": [20, 22, 21, 23],
    "Faculty": ["Engineering", "Medicine", "Law", "Business"]
}
df = pd.DataFrame(Data)

# Add Serial Number
df.insert(0, "S.N", range(1, len(df) + 1))

# Print without default index
print(df.to_string(index=False))

 S.N    Name  Age     Faculty
   1 Subhash   20 Engineering
   2   Kumar   22    Medicine
   3    Ravi   21         Law
   4    Anil   23    Business

In [64]:
# Display the first 3 rows of the data frame
print(df.head(3))

# Display the last 2 rows of the data frame
print(df.tail(2))

   S.N     Name  Age      Faculty
0    1  Subhash   20  Engineering
1    2    Kumar   22     Medicine
2    3     Ravi   21          Law
   S.N  Name  Age   Faculty
2    3  Ravi   21       Law
3    4  Anil   23  Business

In [62]:
# Find the total number of rows and columns in the data frame
print(df.shape)

(4, 4)

In [67]:
#Display all coulumns in the data frame
print(df.columns)

Index(['S.N', 'Name', 'Age', 'Faculty'], dtype='str')

In [68]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   S.N      4 non-null      int64
 1   Name     4 non-null      str
 2   Age      4 non-null      int64
 3   Faculty  4 non-null      str
dtypes: int64(2), str(2)
memory usage: 260.0 bytes

In [69]:
df.describe()   #std(standard deviation), mean, min, max, 25%(Percentile), 50%(Median), 75%(3rd Quartile),  of the data frame

            S.N        Age
count  4.000000   4.000000
mean   2.500000  21.500000
std    1.290994   1.290994
min    1.000000  20.000000
25%    1.750000  20.750000
50%    2.500000  21.500000
75%    3.250000  22.250000
max    4.000000  23.000000

In [70]:
df['Name']

0    Subhash
1      Kumar
2       Ravi
3       Anil
Name: Name, dtype: str

In [71]:
df[['Name', 'Age']] #selecting multiple columns from the data frame

      Name  Age
0  Subhash   20
1    Kumar   22
2     Ravi   21
3     Anil   23

In [72]:
df.iloc[0]  #selecting the first row of the data frame

S.N                  1
Name           Subhash
Age                 20
Faculty    Engineering
Name: 0, dtype: object

In [73]:
df.loc[0]  #selecting the first row of the data frame using loc() method

S.N                  1
Name           Subhash
Age                 20
Faculty    Engineering
Name: 0, dtype: object

In [74]:
df.loc[0, 'Name']  #selecting the value of the "Name" column in the first row of the data frame using loc() method

'Subhash'

In [76]:
df[df['Age'] > 20]  #selecting the row with the minimum value in the "Age" column

   S.N   Name  Age   Faculty
1    2  Kumar   22  Medicine
2    3   Ravi   21       Law
3    4   Anil   23  Business

In [78]:
# Add Mark column to the data frame
df['Marks'] = [85, 90, 78, 92]
my_df = pd.DataFrame({

})
print(df)

   S.N     Name  Age      Faculty  Marks
0    1  Subhash   20  Engineering     85
1    2    Kumar   22     Medicine     90
2    3     Ravi   21          Law     78
3    4     Anil   23     Business     92

In [79]:
df[(df['Age'] > 20) & (df['Marks'] > 75)]

   S.N   Name  Age   Faculty  Marks
1    2  Kumar   22  Medicine     90
2    3   Ravi   21       Law     78
3    4   Anil   23  Business     92

In [80]:
df['Grade'] = ['A', 'A+', 'B', 'A+'] #Adding a new column "Grade" to the data frame with the values "A", "A+", "B", and "A+" for each row respectively
print(df)

   S.N     Name  Age      Faculty  Marks Grade
0    1  Subhash   20  Engineering     85     A
1    2    Kumar   22     Medicine     90    A+
2    3     Ravi   21          Law     78     B
3    4     Anil   23     Business     92    A+

In [82]:
df['Marks'] = df['Marks'] + 5  #Adding 5 marks to each value in the "Marks" column of the data frame
print(df)

   S.N     Name  Age      Faculty  Marks Grade
0    1  Subhash   20  Engineering     95     A
1    2    Kumar   22     Medicine    100    A+
2    3     Ravi   21          Law     88     B
3    4     Anil   23     Business    102    A+

In [83]:
# Adding 5 marks to the first row
df.loc[0, 'Marks'] = df.loc[0, 'Marks'] + 5
print(df)

   S.N     Name  Age      Faculty  Marks Grade
0    1  Subhash   20  Engineering    100     A
1    2    Kumar   22     Medicine    100    A+
2    3     Ravi   21          Law     88     B
3    4     Anil   23     Business    102    A+

In [84]:
df.loc[df['Name'] == 'Kumar', 'Marks'] = df.loc[df['Name'] == 'Kumar', 'Marks'] + 5
print(df) #Adding 5 marks to the row where the "Name" column has the value "Kumar" in the data frame

   S.N     Name  Age      Faculty  Marks Grade
0    1  Subhash   20  Engineering    100     A
1    2    Kumar   22     Medicine    105    A+
2    3     Ravi   21          Law     88     B
3    4     Anil   23     Business    102    A+

In [88]:
df1=df.drop('Age', axis=1, )  # Removing the "Age" column from the data frame
print(df1)

   S.N     Name      Faculty  Marks Grade
0    1  Subhash  Engineering    100     A
1    2    Kumar     Medicine    105    A+
2    3     Ravi          Law     88     B
3    4     Anil     Business    102    A+

In [89]:
# Remove the first row without modifying the original DataFrame
df_no_first = df.drop(index=0)
print("Without first row:\n", df_no_first)

# Sort by Marks ascending
df_sorted_asc = df.sort_values(by='Marks', ascending=True).reset_index(drop=True)
print("\nSorted by Marks (asc):\n", df_sorted_asc)

# Sort by Marks descending
df_sorted_desc = df.sort_values(by='Marks', ascending=False).reset_index(drop=True)
print("\nSorted by Marks (desc):\n", df_sorted_desc)

# Concatenate another DataFrame with matching columns
df2 = pd.DataFrame({
    'S.N': [5],
    'Name': ['Neha'],
    'Age': [24],
    'Faculty': ['Science'],
    'Marks': [95],
    'Grade': ['A']
})

df_concat = pd.concat([df, df2], ignore_index=True)
print("\nConcatenated DataFrame:\n", df_concat)

Without first row:
    S.N   Name  Age   Faculty  Marks Grade
1    2  Kumar   22  Medicine    105    A+
2    3   Ravi   21       Law     88     B
3    4   Anil   23  Business    102    A+

Sorted by Marks (asc):
    S.N     Name  Age      Faculty  Marks Grade
0    3     Ravi   21          Law     88     B
1    1  Subhash   20  Engineering    100     A
2    4     Anil   23     Business    102    A+
3    2    Kumar   22     Medicine    105    A+

Sorted by Marks (desc):
    S.N     Name  Age      Faculty  Marks Grade
0    2    Kumar   22     Medicine    105    A+
1    4     Anil   23     Business    102    A+
2    1  Subhash   20  Engineering    100     A
3    3     Ravi   21          Law     88     B

Concatenated DataFrame:
    S.N     Name  Age      Faculty  Marks Grade
0    1  Subhash   20  Engineering    100     A
1    2    Kumar   22     Medicine    105    A+
2    3     Ravi   21          Law     88     B
3    4     Anil   23     Business    102    A+
4    5     Neha   24      Science     95     A